export const COLLECTIONS = {
  USERS: 'users',
  COMPANIES: 'companies',
  CARS: 'cars',
  TRAVELS: 'travels',
  INCLUDED_SERVICES: 'includedServices',
  HOTELS: 'hotels',
  ROOMS: 'rooms',
  FOOD_ITEMS: 'foodItems',
  ORDERS: 'orders',
  PAYMENT_METHODS: 'paymentMethods',
  TRANSACTIONS: 'transactions',
  REVIEWS: 'reviews',
  EXCHANGE_RATES: 'exchangeRates',
  USER_INTERESTS: 'userInterests',
  APP_CONFIG: 'appConfig',
  BANNERS: 'banners',
  UPLOADS: 'uploads',
  CATEGORIES: 'categories',
  HOME_SECTIONS: 'homeSections',
  WISHLIST: 'wishlist',
} as const;

