import type { OrderScreenKey } from '../modules/order/order.schema.js';

export const ORDER_SCREENS: Record<'RENT_A_CAR' | 'TRAVEL' | 'HOTEL_ROOM' | 'FOOD', OrderScreenKey[]> = {
  RENT_A_CAR: ['PERSONAL_INFO_SCREEN', 'DRIVER_LICENSE_SCREEN', 'ADDRESS_SCREEN', 'PAYMENT_SCREEN', 'CONFIRM_SCREEN'],
  TRAVEL: ['PERSONAL_INFO_SCREEN', 'PASSPORT_INFO_SCREEN', 'PAYMENT_SCREEN', 'CONFIRM_SCREEN'],
  HOTEL_ROOM: ['PERSONAL_INFO_SCREEN', 'PAYMENT_SCREEN', 'CONFIRM_SCREEN'],
  FOOD: ['PERSONAL_INFO_SCREEN', 'DELIVERY_ADDRESS_SCREEN', 'PAYMENT_SCREEN', 'CONFIRM_SCREEN'],
};
