import { OpenAPIRegistry } from '@asteasolutions/zod-to-openapi';
import { addAdminSchema, adminTransactionQuerySchema } from '../modules/admin/admin.schema.js';
import { appConfigSchema } from '../modules/appConfig/appConfig.schema.js';
import { registerSchema, loginSchema, refreshSchema, googleLoginSchema } from '../modules/auth/auth.schema.js';
import { foodItemsQuerySchema, createFoodCompanySchema, updateFoodCompanySchema, createFoodItemSchema, updateFoodItemSchema } from '../modules/food/food.schema.js';
import { createBannerSchema, updateBannerSchema } from '../modules/home/home.schema.js';
import { hotelQuerySchema, roomQuerySchema, createHotelSchema, updateHotelSchema, createRoomSchema, updateRoomSchema } from '../modules/hotel/hotel.schema.js';
import { createOrderSchema, advanceStepSchema, updateOrderStatusSchema, adminOrderQuerySchema } from '../modules/order/order.schema.js';
import { addCardSchema, paySchema } from '../modules/payment/payment.schema.js';
import { carsQuerySchema, createCompanySchema, updateCompanySchema, createCarSchema, updateCarSchema } from '../modules/rentacar/rentacar.schema.js';
import { createReviewSchema, reviewQuerySchema, updateReviewSchema } from '../modules/reviews/reviews.schema.js';
import { toursQuerySchema, includedServicesParamsSchema, createTravelCompanySchema, updateTravelCompanySchema, createTourSchema, updateTourSchema, createIncludedServiceSchema, updateIncludedServiceSchema, includedServiceIdParamsSchema } from '../modules/travel/travel.schema.js';
import { updateProfileSchema, profileCompletenessSchema } from '../modules/users/users.schema.js';
import { addToWishlistSchema } from '../modules/wishlist/wishlist.schema.js';
import { categoriesQuerySchema, createCategorySchema, updateCategorySchema } from '../modules/categories/categories.schema.js';

export const registry = new OpenAPIRegistry();

registry.register('AddAdminInput', addAdminSchema);
registry.register('AdminTransactionQuery', adminTransactionQuerySchema);
registry.register('AppConfigInput', appConfigSchema);
registry.register('RegisterInput', registerSchema);
registry.register('LoginInput', loginSchema);
registry.register('RefreshInput', refreshSchema);
registry.register('GoogleLoginInput', googleLoginSchema);
registry.register('FoodItemsQuery', foodItemsQuerySchema);
registry.register('CreateFoodCompanyInput', createFoodCompanySchema);
registry.register('UpdateFoodCompanyInput', updateFoodCompanySchema);
registry.register('CreateFoodItemInput', createFoodItemSchema);
registry.register('UpdateFoodItemInput', updateFoodItemSchema);
registry.register('CreateBannerInput', createBannerSchema);
registry.register('UpdateBannerInput', updateBannerSchema);
registry.register('HotelQuery', hotelQuerySchema);
registry.register('RoomQuery', roomQuerySchema);
registry.register('CreateHotelInput', createHotelSchema);
registry.register('UpdateHotelInput', updateHotelSchema);
registry.register('CreateRoomInput', createRoomSchema);
registry.register('UpdateRoomInput', updateRoomSchema);
registry.register('CreateOrderInput', createOrderSchema);
registry.register('AdvanceOrderStepInput', advanceStepSchema);
registry.register('UpdateOrderStatusInput', updateOrderStatusSchema);
registry.register('AdminOrderQuery', adminOrderQuerySchema);
registry.register('AddCardInput', addCardSchema);
registry.register('PayInput', paySchema);
registry.register('CarsQuery', carsQuerySchema);
registry.register('CreateRentACarCompanyInput', createCompanySchema);
registry.register('UpdateRentACarCompanyInput', updateCompanySchema);
registry.register('CreateCarInput', createCarSchema);
registry.register('UpdateCarInput', updateCarSchema);
registry.register('CreateReviewInput', createReviewSchema);
registry.register('ReviewQuery', reviewQuerySchema);
registry.register('UpdateReviewInput', updateReviewSchema);
registry.register('ToursQuery', toursQuerySchema);
registry.register('IncludedServicesParams', includedServicesParamsSchema);
registry.register('CreateTravelCompanyInput', createTravelCompanySchema);
registry.register('UpdateTravelCompanyInput', updateTravelCompanySchema);
registry.register('CreateTourInput', createTourSchema);
registry.register('UpdateTourInput', updateTourSchema);
registry.register('CreateIncludedServiceInput', createIncludedServiceSchema);
registry.register('UpdateIncludedServiceInput', updateIncludedServiceSchema);
registry.register('IncludedServiceIdParams', includedServiceIdParamsSchema);
registry.register('UpdateProfileInput', updateProfileSchema);
registry.register('ProfileCompleteness', profileCompletenessSchema);
registry.register('AddToWishlistInput', addToWishlistSchema);
registry.register('CategoriesQuery', categoriesQuerySchema);
registry.register('CreateCategoryInput', createCategorySchema);
registry.register('UpdateCategoryInput', updateCategorySchema);
